openapi: 3.0.0
info:
  title: Oxpress Test API
  version: 1.0.0
paths:
  /v1/users/{userId}:
    get:
      description: |
        ## Get user details
        This endpoint returns the user details
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      responses: 
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string

        age:
          type: integer

        name:
          type: string
      required:
        - "id"
        - "age"
        - "name"

