import { GeneratorPart, GeneratorPartOptions } from "../types";

export class GeneratedFileCommentPart implements GeneratorPart {
  async visit({ output }: GeneratorPartOptions): Promise<void> {
    output.addHeader(`/**
This file was auto-generated by the package "oxpress".
Do not edit this file directly.
*/
`);
  }
}
