name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test
      run: npm test -- --coverage
    - name: Publish coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}